# Write a function to compute 5/0 and use try/except to catch the exceptions.

In [13]:
def Divide():
    return 5/0
try:
    Devide()
except:
    print ("The number is divided by zero")
finally:
    print ('In the finally block')

The number is divided by zero
In the finally block


# Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [14]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

l=[(a +" "+ b +" "+ c) for a in subject for b in verb for c in obj]
for i in l:
    print(i)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


# Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, whenincreasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [15]:
import numpy as np 

In [17]:
def matrix(m,n,increasing =False):
    if not increasing:
        mat = np.array([x**(n-1-i) for x in m for i in range(n)]).reshape(len(m),n)
    elif increasing:
        mat = np.array([x**i for x in m for i in range(n)]).reshape(len(m),n)
    return mat

l = np.array([1,2,3,4,5])
col = 5
dec_order = matrix(l,col,False)
inc_order = matrix(l,col,True)

print("matrix in decreasing order of powers:\n\n",dec_order,"\n")
print("matrix in increasing order of powers:\n\n",inc_order,"\n")

matrix in decreasing order of powers:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

matrix in increasing order of powers:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 

